import AppLayout from "@/components/layout/AppLayout";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Warehouse</title>
      <meta
        name="viewport"
        content="width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover"
      />
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
